### ISSUE TITLE
前后端不是同一个人写的吧，很多地方对不上，表设计也有问题

### ISSUE THREAD

**Issue by foryo77** [supervons/ExploreKoa#1]
比如更新用户信息接口

**Comment by supervons** [comment]
1.  是同一个人写的，前端用的是 [ExploreRN](https://github.com/supervons/ExploreRN) 吗？
2.  数据库我也是在持续学习中，有不合理的地方可以提出来，或者给一个 `PR`，一起学习进步。

**Comment by foryo77** [comment]
是[ExploreRN](https://github.com/supervons/ExploreRN)，设计表的时候有些字段没给默认值也没有允许为NULL....

**Comment by supervons** [comment]
1. [ExploreRN](https://github.com/supervons/ExploreRN)更新用户信息就是：api/v1/profile ，后续会给一份对应的文档；
2. 没有给默认值且不让为 `NULL` 的字段，是在初始化出现问题了吗？至于给默认值，可以说说想法讨论讨论。

**Comment by foryo77** [comment]
create_time应该给个now()

**Comment by supervons** [comment]
有道理，这样时间就不用手动赋值了，后面看看改一改。

**Comment by supervons** [comment]
已修改，可用查看：https://github.com/supervons/ExploreKoa/commit/1f773cb31b0031806bbf1accc7d5a0679dc24b3e

值得注意的，`MySQL` 在 `5.7` 之后的版本才支持创建的时候使用 `now()` 函数自动给时间赋值，后续测试后会在文档指出。
